
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: dannypark92@gmail.com
    http01: {}
    privateKeySecretRef:
      key: ""
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
